name: multiavatar
description: Multiavatar is a multicultural avatar maker. 12 billion unique multicultural avatars 
version: 0.1.4
homepage: https://github.com/X-SLAYER/Multiavatar
documentation: https://github.com/X-SLAYER/Multiavatar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
